# Define o path raiz da aplicação JAX-RS
quarkus.http.root-path=/

# Configuração do SmallRye JWT
smallrye.jwt.sign.algorithm=HS256

# Define o emissor (issuer) padrão para validação
mp.jwt.verify.issuer=https://example.com/issuer

# Native Image Configuration
quarkus.native.additional-build-args=--initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder, -march=x86-64-v3

# DynamoDB Configuration
quarkus.dynamodb.aws.region=us-east-1
# Force usage of URL Connection Client
quarkus.dynamodb.sync-client.type=url
quarkus.dynamodb.table-name=users

# Disable Dev Services for DynamoDB (we are using manual Testcontainers)
quarkus.dynamodb.devservices.enabled=false

# JWT Secret for testing (and default dev)
JWT_SECRET=mySuperSecretKeyForTestingPurposesOnly1234567890

# Desabilitar autenticação proativa para evitar que o Quarkus tente validar o token automaticamente
# antes de chegar no nosso endpoint manual, já que não configuramos a validação globalmente.
quarkus.http.auth.proactive=false
