# Define o path raiz da aplicação JAX-RS
quarkus.http.root-path=/

# Native Image Configuration
quarkus.native.additional-build-args=--initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder

# DynamoDB Configuration
quarkus.dynamodb.aws.region=us-east-1
# Force usage of URL Connection Client
quarkus.dynamodb.sync-client.type=url
