# Define o path raiz da aplicação JAX-RS
quarkus.http.root-path=/

# Configuração do SmallRye JWT
# Aponta para o arquivo no classpath que contém a chave secreta em texto plano
smallrye.jwt.sign.algorithm=HS256
# Configura a verificação para usar a mesma chave secreta (HS256)
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.verify.key=${JWT_SECRET}

# Define o emissor (issuer) padrão para validação
mp.jwt.verify.issuer=https://example.com/issuer

# Native Image Configuration
quarkus.native.additional-build-args=--initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder

# DynamoDB Configuration
quarkus.dynamodb.aws.region=us-east-1
# Force usage of URL Connection Client
quarkus.dynamodb.sync-client.type=url
